Feature/add network part
p0l0satik/SphericalProjectionPlaneSegmentator pull request #5
Opened 2023-10-24 13:52 UTC by p0l0satik

2023-10-24 15:59 UTC, kirill-ivanov-a requested changes

2023-10-24 15:59 UTC, kirill-ivanov-a commented on loader/dataset.py
> +            return cloud["proj_points"], cloud["proj_labels"],cloud["points"],cloud["labels"], cloud["proj_idx"]
There is not a space after the comma everywhere. All these minor inaccuracies in syntax can be corrected by a linter :)

2023-10-24 15:59 UTC, kirill-ivanov-a commented on loader/dataset.py
> +        return  cloud["proj_points"],cloud["proj_labels"],
why extra comma?

2023-10-24 15:59 UTC, kirill-ivanov-a commented on network/common_blocks.py
> +    return model, optimizer, scheduler
The return type doesn't seem to match the function name

2023-10-24 15:59 UTC, kirill-ivanov-a commented on network/common_blocks.py
> +def one_epoch(config, loader, optimizer, model, criterion=None, train_mode=True):
The function name usually reflects some action

2023-10-24 15:59 UTC, kirill-ivanov-a commented on network/common_blocks.py
> +    tl,
What do tl and vl mean? It's better to call it more expressively

2023-10-24 15:59 UTC, kirill-ivanov-a commented on network/config.py
> +            # TODO: log all parameters
Before merging, TODO must either be removed or implemented

2023-10-24 15:59 UTC, kirill-ivanov-a commented on loader/dataset.py
> -            return SphericalProjectionReturnValue(
Why did you decide to abandon the class for the return value?

2023-10-24 15:59 UTC, kirill-ivanov-a commented on network/common_blocks.py
> +import torch
It seems to me that you can create a class that will perform training, validation, and so on. In order not to pass the same parameters everywhere

2023-10-31 11:21 UTC, p0l0satik commented on loader/dataset.py
> -            return SphericalProjectionReturnValue(
It was done so torch Dataloader does not support torch Dataset to return Classes by default. https://stackoverflow.com/questions/72867109/what-is-pytorch-dataset-supposed-to-return https://github.com/pytorch/pytorch/blob/main/torch/utils/data/_utils/collate.py#L85-L130 So I decided to revert and leave as it was

2023-10-31 15:11 UTC, kirill-ivanov-a approved these changes

2023-10-31 15:12 UTC, merged